services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - ./config:/config
      - /opt/stacks/shared/downloads:/downloads
      - /mnt/Media/TV:/tv
    networks:
      - proxy
    restart: always

networks:
  proxy:
    name: proxy
    external: true
