services:
  tsidp:
    image: ghcr.io/tailscale/tsidp:latest
    container_name: tsidp
    user: "0:0"
    env_file: ../.env
    environment:
      - TAILSCALE_USE_WIP_CODE=1
      - TS_HOSTNAME=tsidp
      - TS_STATE_DIR=/data
      - TSIDP_ENABLE_STS=1
      - TSIDP_DEBUG_ALL_REQUESTS=1
    volumes:
      - ./data:/data
    restart: unless-stopped
