services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - ./downloads:/downloads #optional
    ports:
      - "192.168.1.102:8081:8081"
      - 6881:6881
      - 6881:6881/udp
    stop_grace_period: "10s" #optional
    restart: unless-stopped
