services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - ./config:/config
    labels:
      tsdproxy.enable: "true"
      tsdproxy.port.1: "443/https:9696/http"
    networks:
      - default
      - shared
    restart: always

networks:
  default:
  shared:
    name: homelab
    external: true
