services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - ./config:/config
    networks:
      - proxy
    ports:
      - "192.168.1.102:9696:9696"
    restart: always

networks:
  proxy:
    name: proxy
    external: true
