services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - ./config:/config
      - /opt/stacks/shared/downloads:/downloads
      - /opt/stacks/shared/incomplete-downloads:/incomplete-downloads
    networks:
      - proxy
    ports:
      - "192.168.1.102:8080:8080"
    restart: always

networks:
  proxy:
    name: proxy
    external: true
