services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 0:0
    restart: unless-stopped
    volumes:
      - "./config:/data"
      - "/mnt/Media/Music:/music:ro"
    ports:
      - "192.168.1.102:4533:4533"
    env_file: .env
    environment:
      ND_COVERARTPRIORITY: cover.*, folder.*, front.*, embedded
      ND_SPOTIFY_ID: ${ND_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${ND_SPOTIFY_SECRET}
      ND_ENABLEEXTERNALSERVICES: true
