services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 0:0
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "navidrome"
      tsdproxy.port.1: "443/https:4533/http"
    volumes:
      - "./config:/data"
      - "/mnt/Media/Music:/music:ro"
    networks:
      - shared
    env_file: .env
    environment:
      ND_COVERARTPRIORITY: folder.*
      ND_SPOTIFY_ID: ${ND_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${ND_SPOTIFY_SECRET}
      ND_ENABLEEXTERNALSERVICES: true

networks:
  shared:
    name: homelab
    external: true
