services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.mccrea.link
      PUID: 1000
      PGID: 1000
    env_file:
      - path: .env
        required: false
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    ports:
      - "192.168.1.102:3000:3000"
    restart: always

networks:
  proxy:
    name: proxy
    external: true
