---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - JELLYFIN_PublishedServerUrl=https://jellyfin.mccrea.link
    volumes:
      - ./config:/config
      - /mnt/Media/TV:/data/tvshows
      - /mnt/Media/Movies:/data/movies
    devices:
      - /dev/dri:/dev/dri
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    external: true
