---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - JELLYFIN_PublishedServerUrl=https://jellyfin.tailfab2f.ts.net
    volumes:
      - ./config:/config
      - /mnt/Media/TV:/data/tvshows
      - /mnt/Media/Movies:/data/movies
    ports:
      - 8100:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
    labels:
      tsdproxy.enable: "true"
      tsdproxy.port.1: "443/https:8100/http"
    networks:
      - default
      - shared
    restart: unless-stopped

networks:
  default:
  shared:
    name: tsidp_bridge
    external: true
