---
services:
  tailscale-jellyfin:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: tailscale-jellyfin
    hostname: jellyfin
    env_file: ../.env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_EXTRA_ARGS=--accept-dns=false
    volumes:
      - ./tailscale/state:/var/lib/tailscale
      - ./tailscale/config:/config
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - JELLYFIN_PublishedServerUrl=https://jellyfin.tailfab2f.ts.net
    volumes:
      - ./config:/config
      - /mnt/Media/TV:/data/tvshows
      - /mnt/Media/Movies:/data/movies
    devices:
      - /dev/dri:/dev/dri
    network_mode: service:tailscale-jellyfin
    depends_on:
      - tailscale-jellyfin
    restart: unless-stopped
