---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Trackers:
    - MyAnonaMouse:
        - abbr: MAM
          href: https://www.myanonamouse.net/
