---
- Infrastructure:
    - Proxmox VE:
        href: https://pve.mccrea.link
        siteMonitor: https://192.168.1.100:8006
        statusStyle: "dot"
        icon: proxmox.svg
    - OpenMediaVault:
        href: https://omv.mccrea.link
        siteMonitor: http://192.168.1.104
        statusStyle: "dot"
        icon: openmediavault.svg
    - AdGuard Home:
        href: https://adguard.mccrea.link
        siteMonitor: http://192.168.1.105
        statusStyle: "dot"
        icon: adguard-home.svg
    - Beszel:
        href: https://beszel.mccrea.link
        siteMonitor: http://192.168.1.102:8090
        statusStyle: "dot"
        icon: beszel.svg

- Documents:
    - BookStack:
        href: https://wiki.mccrea.link
        siteMonitor: https://wiki.mccrea.link
        statusStyle: "dot"
        icon: bookstack.svg
    - Paperless-ngx:
        href: https://paperless.mccrea.link
        siteMonitor: http://192.168.1.102:8000
        statusStyle: "dot"
        icon: paperless-ngx.svg

- Home Automation:
    - Home Assistant:
        href: https://hass.mccrea.link
        siteMonitor: http://192.168.1.103:8123
        statusStyle: "dot"
        icon: home-assistant.svg

- Media:
    - Jellyfin:
        href: https://jellyfin.mccrea.link
        siteMonitor: http://192.168.1.102:8096
        statusStyle: "dot"
        icon: jellyfin.svg
    - Navidrome:
        href: https://navidrome.mccrea.link
        siteMonitor: http://192.168.1.102:4533
        statusStyle: "dot"
        icon: navidrome.svg
    - Immich:
        href: https://immich.mccrea.link
        siteMonitor: http://192.168.1.102:2283
        statusStyle: "dot"
        icon: immich.svg
    - SABnzbd:
        href: https://sabnzbd.mccrea.link
        siteMonitor: http://192.168.1.102:8080/sabnzbd/
        statusStyle: "dot"
        icon: sabnzbd.svg
    - Radarr:
        href: https://radarr.mccrea.link
        siteMonitor: http://192.168.1.102:7878
        statusStyle: "dot"
        icon: radarr.svg
    - Sonarr:
        href: https://sonarr.mccrea.link
        siteMonitor: http://192.168.1.102:8989
        statusStyle: "dot"
        icon: sonarr.svg
    - Prowlarr:
        href: https://prowlarr.mccrea.link
        siteMonitor: http://192.168.1.102:9696
        statusStyle: "dot"
        icon: prowlarr.svg
