---
- Infrastructure:
    - Tailscale IDP:
        href: https://100.88.0.39
        icon: tailscale.svg
    - Proxmox VE:
        href: https://100.92.229.102:8006
        icon: proxmox.svg
    - OpenMediaVault:
        href: http://192.168.1.104
        siteMonitor: http://192.168.1.104
        statusStyle: "dot"
        icon: openmediavault.svg
    - AdGuard Home:
        href: http://100.64.31.2
        siteMonitor: http://100.64.31.2
        statusStyle: "dot"
        icon: adguard-home.svg
    - Beszel:
        href: http://100.98.242.21:8090
        siteMonitor: http://100.98.242.21:8090
        statusStyle: "dot"
        icon: beszel.svg

- Documents:
    - BookStack:
        href: https://wiki.mccrea.link
        siteMonitor: https://wiki.mccrea.link
        statusStyle: "dot"
        icon: bookstack.svg
    - Paperless-ngx:
        href: http://100.95.0.84:8000
        siteMonitor: http://100.95.0.84:8000
        statusStyle: "dot"
        icon: paperless-ngx.svg
    - Stirling PDF:
        href: http://100.103.220.108:8080
        siteMonitor: http://100.103.220.108:8080
        statusStyle: "dot"
        icon: stirling-pdf.svg

- Home Automation:
    - Home Assistant:
        href: http://192.168.1.103:8123
        siteMonitor: http://192.168.1.103:8123
        statusStyle: "dot"
        icon: home-assistant.svg

- Media:
    - Jellyfin:
        href: http://100.86.11.60:8096
        siteMonitor: http://100.86.11.60:8096
        statusStyle: "dot"
        icon: jellyfin.svg
    - Navidrome:
        href: http://100.119.32.95:4533
        siteMonitor: http://100.119.32.95:4533
        statusStyle: "dot"
        icon: navidrome.svg
    - Immich:
        href: http://100.85.34.58:2283
        siteMonitor: http://100.85.34.58:2283
        statusStyle: "dot"
        icon: immich.svg
    - SABnzbd:
        href: http://100.85.220.21:8080
        siteMonitor: http://100.85.220.21:8080
        statusStyle: "dot"
        icon: sabnzbd.svg
    - Radarr:
        href: http://100.118.118.93:7878
        siteMonitor: http://100.118.118.93:7878
        statusStyle: "dot"
        icon: radarr.svg
    - Sonarr:
        href: http://100.109.247.96:8989
        siteMonitor: http://100.109.247.96:8989
        statusStyle: "dot"
        icon: sonarr.svg
    - Prowlarr:
        href: http://100.103.138.106:9696
        siteMonitor: http://100.103.138.106:9696
        statusStyle: "dot"
        icon: prowlarr.svg
